### ISSUE TITLE
How use the PyroCMS Language Switcher?

### ISSUE THREAD

**Issue by thallysondias** [afbora/PyroCMS-Language-Switcher-Plugin#3]
(In pyro2.2)

I installed the plugin on my site, but do not understand how it works

-I created a new Custon Field (atacchament).
(yes or no, i dont undestand this questions)

-Add new post and click Custon Field. HAve just 1 select for language e dont have text area.

How i type text for others languages?

![new-field](https://cloud.githubusercontent.com/assets/1922433/4121837/cad0a592-32be-11e4-853a-50e272d18a88.PNG)

![new-post](https://cloud.githubusercontent.com/assets/1922433/4121838/cad0d968-32be-11e4-88b8-c4c7c3dd2b22.PNG)

**Comment by afbora** [comment]
This is a "Plugin" not "Field Type". You have tried PyroCMS Language field type.

This plugin works only switch the current language on frontend.
